import express from "express";
import analyticsRoutes from "./analyticsRoutes.js";
import authRoutes from "./authRoutes.js";
import userRoutes from "./userRoutes.js";
import rolePermissionRoutes from "./rolePermissionRoutes.js";
import adminRoutes from "./adminRoutes.js";
import auditLogRoutes from "./auditLogRoutes.js";
import categoryRoutes from "./categoryRoutes.js";
import productRoutes from "./productRoutes.js";
import menuRoutes from "./menuRoutes.js";
import inventoryRoutes from "./inventoryRoutes.js";
import couponRoutes from "./couponRoutes.js";
import wishlistRoutes from "./wishlistRoutes.js";
import reviewRoutes from "./reviewRoutes.js";
import cartRoutes from "./cartRoutes.js";
import checkoutRoutes from "./checkoutRoutes.js";
import orderRoutes from "./orderRoutes.js";
import paymentRoutes from "./paymentRoutes.js";
import webhookRoutes from "./webhookRoutes.js";
import shippingRoutes from "./shippingRoutes.js";
import addressRoutes from "./addressRoutes.js";
import notificationRoutes from "./notificationRoutes.js";
import contactRoutes from "./contactRoutes.js";
import feedbackRoutes from "./feedbackRoutes.js";
import returnsRoutes from "./returnsRoutes.js";
import refundRoutes from "./refundRoutes.js";

const router = express.Router();
router.use("/analytics", analyticsRoutes);
router.use("/auth", authRoutes);
router.use("/user", userRoutes);
router.use("/roles", rolePermissionRoutes);
router.use("/admin", adminRoutes);
router.use("/auditLog", auditLogRoutes);
router.use("/category", categoryRoutes);
router.use("/product", productRoutes);
router.use("/menu", menuRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/coupon", couponRoutes);
router.use("/wishlist", wishlistRoutes);
router.use("/review", reviewRoutes);
router.use("/cart", cartRoutes);
router.use("/checkout", checkoutRoutes);
router.use("/order", orderRoutes);
router.use("/payment", paymentRoutes);
router.use("/webhook", webhookRoutes);
router.use("/shipping", shippingRoutes);
router.use("/address", addressRoutes);
router.use("/notification", notificationRoutes);
router.use("/contact", contactRoutes);
router.use("/feedback", feedbackRoutes);
router.use("/returns", returnsRoutes);
router.use("/refund", refundRoutes);

export default router;
